### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by Aariion** [Masster51/Universal-Bot#1]
We need to start somewhere so. Lets do a checklist
- [x] Start project
- [x] Get it running
- [x] Optimize

**Comment by Masster51** [comment]
Yea, thats what we need. I send you more information later.

**Comment by UkrainianBanderasCat** [comment]
Hi

**Comment by UkrainianBanderasCat** [comment]
Whats a bot name?

**Comment by Masster51** [comment]
Universal Bot
